USE [master]
GO

/****** Object:  Database [Escola]    Script Date: 16/08/2020 17:39:20 ******/
CREATE DATABASE [Escola]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Escola', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Escola.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Escola_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Escola_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Escola].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Escola] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Escola] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Escola] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Escola] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Escola] SET ARITHABORT OFF 
GO

ALTER DATABASE [Escola] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Escola] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Escola] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Escola] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Escola] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Escola] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Escola] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Escola] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Escola] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Escola] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Escola] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Escola] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Escola] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Escola] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Escola] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Escola] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Escola] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Escola] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Escola] SET  MULTI_USER 
GO

ALTER DATABASE [Escola] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Escola] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Escola] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Escola] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Escola] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Escola] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Escola] SET  READ_WRITE 
GO

